# Generated by Django 5.1.3 on 2024-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_badge_category_question_option_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='difficulty_level',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
    ]
