[project]
name = "server"
version = "0.1.0"
description = "Backend for the project: Django and Django Ninja"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.1.3",
    "django-cors-headers>=4.6.0",
    "django-ninja>=1.3.0",
    "psycopg2-binary>=2.9.10",
]
